import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {parse} from 'acorn';
import {resolveCoreBundle} from './_assetRefs.mjs';
const source=readFileSync(resolveCoreBundle().path,'utf8');
const ast=parse(source,{ecmaVersion:'latest'}),fn=ast.body.find(n=>n.type==='FunctionDeclaration'&&n.id.name==='_searchLocalPokemon');
let factory,rows=[{id:'set-1',n:'Mew',s:'Exact set',si:'set',nu:'001a',g:'pokemon',i:'https://example.test/card.png'},{id:'other',n:'Mew',g:'mtg'}],current=true;
const c={window:{CardResellFastPath:{loadCardIndex:async game=>{assert.equal(game,'pokemon');return rows}}},dropList:{innerHTML:''},_searchReqStillCurrent:()=>current,esc:s=>String(s).replace(/</g,'&lt;'),attachDropHandlers:f=>{factory=f}};
vm.createContext(c);vm.runInContext(source.slice(fn.start,fn.end),c);let checks=0;
const check=(label,a,b)=>{assert.deepEqual(a,b,label);checks++;console.log('✓ '+label)};
check('outage has a usable identity fallback',await c._searchLocalPokemon('Mew',1),true);
check('fallback discloses limited coverage',c.dropList.innerHTML.includes('limited local catalog'),true);
check('only Pokemon records used',Object.keys(c.window._searchCards).length,1);
check('collector suffix retained',factory(0).number,'001a');
check('no invented prices',factory(0).priceVariants.length,0);
check('local source explicit',factory(0).source.includes('live prices unavailable'),true);
check('exact canonical id retained',factory(0).id,'set-1');
current=false;c.dropList.innerHTML='new search';await c._searchLocalPokemon('Mew',1);
check('late response cannot replace new query',c.dropList.innerHTML,'new search');
current=true;rows=[];check('local miss does not assert global absence',await c._searchLocalPokemon('unknown',1),false);
c.window.CardResellFastPath.loadCardIndex=async()=>{throw Error('offline')};check('failed optional index preserves provider error',await c._searchLocalPokemon('Mew',1),false);
c.window.CardResellFastPath.loadPokemonMetadata=async()=>[{id:'missing-image',g:'pokemon',n:'Mew',nu:'HGSS18',s:'Promos'}];
check('metadata-only identity survives image-index failure',await c._searchLocalPokemon('Mew',1),true);
check('metadata-only result remains unpriced',factory(0).priceVariants.length,0);
console.log(`SUITE COMPLETE: catalog-outage.mjs: ${checks} passed, 0 failed`);
